name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  markdown-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@master
    - name: markdownlint-cli
      uses: nosborn/github-action-markdown-cli@v1.1.1
      with:
        config_file: ".github/workflows/markdownlint.json"
        files: .
