name: CI

on:
  pull_request

jobs:
  markdown-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: markdownlint-cli
      uses: nosborn/github-action-markdown-cli@v1.1.1
      with:
        config_file: ".github/workflows/markdownlint.json"
        files: .
